#pragma once
// This file was generated by wc-gen. Do not modify this file manually.
#include "Move.hpp"
#include "Point3.hpp"
#include "TypeId.hpp"
#include <stdint.h>
#include <string>
#include <vector>

class Character 
{
public:
	int32_t sp_attack;
	Point3 *position;
	int32_t attack;
	int32_t defense;
	int32_t level;
	int32_t health;
	std::vector<TypeId> types;
	TypeId *type_id;
	int32_t sp_defense;
	int32_t exp;
	int32_t movement;
	std::vector<Move> moves;
	int32_t speed;
	std::string name;
	Character();
	Character(const Character &other);
	~Character();
	void copy_to(Character &other) const;
	Character clone() const;
	bool operator==(const Character &other) const;
	bool operator!=(const Character &other) const;
	Character &operator=(const Character &other);
};
