#pragma once
// This file was generated by wc-gen. Do not modify this file manually.
#include <string>

class Move 
{
public:
	std::string name;
	Move();
	Move(const Move &other);
	~Move();
	void copy_to(Move &other) const;
	Move clone() const;
	bool operator==(const Move &other) const;
	bool operator!=(const Move &other) const;
	Move &operator=(const Move &other);
};
