#pragma once
// This file was generated by wc-gen. Do not modify this file manually.
#include <stdint.h>

class Point3 
{
public:
	int32_t y;
	int32_t x;
	int32_t z;
	Point3();
	Point3(const Point3 &other);
	~Point3();
	void copy_to(Point3 &other) const;
	Point3 clone() const;
	bool operator==(const Point3 &other) const;
	bool operator!=(const Point3 &other) const;
	Point3 &operator=(const Point3 &other);
};
