#pragma once
// This file was generated by wc-gen. Do not modify this file manually.
#include <stdint.h>

class TypeId 
{
public:
	uint32_t id;
	TypeId();
	TypeId(const TypeId &other);
	~TypeId();
	void copy_to(TypeId &other) const;
	TypeId clone() const;
	bool operator==(const TypeId &other) const;
	bool operator!=(const TypeId &other) const;
	TypeId &operator=(const TypeId &other);
};
