#pragma once
// This file was generated by wc-gen. Do not modify this file manually.
#include "TypeId.hpp"
#include <string>

class Type 
{
public:
	TypeId *id;
	std::string name;
	Type();
	Type(const Type &other);
	~Type();
	void copy_to(Type &other) const;
	Type clone() const;
	bool operator==(const Type &other) const;
	bool operator!=(const Type &other) const;
	Type &operator=(const Type &other);
};
