// This file was generated by wc-gen. Do not modify this file manually.

#include "../TypeId.hpp"

TypeId::TypeId()
{
	id = 0;
}
TypeId::TypeId(const TypeId &other) : TypeId()
{
	other.copy_to(*this);
}
TypeId::~TypeId()
{
}
void TypeId::copy_to(TypeId &other) const
{
	other.id = id;
}
TypeId TypeId::clone() const
{
	TypeId clone;
	copy_to(clone);
	return clone;
}
bool TypeId::operator==(const TypeId &other) const
{
	return id == other.id;
}
bool TypeId::operator!=(const TypeId &other) const
{
	return !(this == &other);
}
TypeId &TypeId::operator=(const TypeId &other)
{
	if (this == &other)
	{
		return *this;
	}
	other.copy_to(*this);
	return *this;
}
