// This file was generated by wc-gen. Do not modify this file manually.

#include "../Type.hpp"

Type::Type()
{
	id = new TypeId();
	name = std::string();
}
Type::Type(const Type &other) : Type()
{
	other.copy_to(*this);
}
Type::~Type()
{
	delete id;
}
void Type::copy_to(Type &other) const
{
	id->copy_to(*other.id);
	other.name = name;
}
Type Type::clone() const
{
	Type clone;
	copy_to(clone);
	return clone;
}
bool Type::operator==(const Type &other) const
{
	return *id == *other.id && name == other.name;
}
bool Type::operator!=(const Type &other) const
{
	return !(this == &other);
}
Type &Type::operator=(const Type &other)
{
	if (this == &other)
	{
		return *this;
	}
	other.copy_to(*this);
	return *this;
}
