// This file was generated by wc-gen. Do not modify this file manually.

#include "../Move.hpp"

Move::Move()
{
	name = std::string();
}
Move::Move(const Move &other) : Move()
{
	other.copy_to(*this);
}
Move::~Move()
{
}
void Move::copy_to(Move &other) const
{
	other.name = name;
}
Move Move::clone() const
{
	Move clone;
	copy_to(clone);
	return clone;
}
bool Move::operator==(const Move &other) const
{
	return name == other.name;
}
bool Move::operator!=(const Move &other) const
{
	return !(this == &other);
}
Move &Move::operator=(const Move &other)
{
	if (this == &other)
	{
		return *this;
	}
	other.copy_to(*this);
	return *this;
}
