// This file was generated by wc-gen. Do not modify this file manually.

#include "../Character.hpp"

Character::Character()
{
	sp_attack = 0;
	position = new Point3();
	attack = 0;
	defense = 0;
	level = 0;
	health = 0;
	types = std::vector<TypeId>();
	type_id = new TypeId();
	sp_defense = 0;
	exp = 0;
	movement = 0;
	moves = std::vector<Move>();
	speed = 0;
	name = std::string();
}
Character::Character(const Character &other) : Character()
{
	other.copy_to(*this);
}
Character::~Character()
{
	delete position;
	delete type_id;
}
void Character::copy_to(Character &other) const
{
	other.sp_attack = sp_attack;
	position->copy_to(*other.position);
	other.attack = attack;
	other.defense = defense;
	other.level = level;
	other.health = health;
	other.types = types;
	type_id->copy_to(*other.type_id);
	other.sp_defense = sp_defense;
	other.exp = exp;
	other.movement = movement;
	other.moves = moves;
	other.speed = speed;
	other.name = name;
}
Character Character::clone() const
{
	Character clone;
	copy_to(clone);
	return clone;
}
bool Character::operator==(const Character &other) const
{
	return sp_attack == other.sp_attack && *position == *other.position && attack == other.attack && defense == other.defense && level == other.level && health == other.health && types == other.types && *type_id == *other.type_id && sp_defense == other.sp_defense && exp == other.exp && movement == other.movement && moves == other.moves && speed == other.speed && name == other.name;
}
bool Character::operator!=(const Character &other) const
{
	return !(this == &other);
}
Character &Character::operator=(const Character &other)
{
	if (this == &other)
	{
		return *this;
	}
	other.copy_to(*this);
	return *this;
}
